"""empty message

Revision ID: 106d46b71b2
Revises: 4d2e5fcbe2e
Create Date: 2015-04-28 08:46:37.253629

"""

# revision identifiers, used by Alembic.
revision = '106d46b71b2'
down_revision = '4d2e5fcbe2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_id', sa.INTEGER(), nullable=False),
    sa.Column('val', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('test_id', name='test_pkey')
    )
    ### end Alembic commands ###
