"""empty message

Revision ID: 2007f71734e
Revises: b8819af8e1
Create Date: 2015-04-28 09:06:51.608332

"""

# revision identifiers, used by Alembic.
revision = '2007f71734e'
down_revision = 'b8819af8e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
