"""empty message

Revision ID: 2474c24c055
Revises: 3afda76bc34
Create Date: 2015-05-02 10:10:16.660007

"""

# revision identifiers, used by Alembic.
revision = '2474c24c055'
down_revision = '3afda76bc34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
