"""empty message

Revision ID: 2926c7cbb64
Revises: 3079a00c99c
Create Date: 2015-05-02 09:43:25.806038

"""

# revision identifiers, used by Alembic.
revision = '2926c7cbb64'
down_revision = '3079a00c99c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
