"""empty message

Revision ID: 2f0711d5e7f
Revises: 3c3d260027e
Create Date: 2015-04-26 22:08:47.138701

"""

# revision identifiers, used by Alembic.
revision = '2f0711d5e7f'
down_revision = '3c3d260027e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'response', 'art', ['art_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response', type_='foreignkey')
    ### end Alembic commands ###
