"""empty message

Revision ID: 3079a00c99c
Revises: c39454cd62
Create Date: 2015-05-02 09:13:09.672100

"""

# revision identifiers, used by Alembic.
revision = '3079a00c99c'
down_revision = 'c39454cd62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
