"""empty message

Revision ID: 30dcafee101
Revises: 2474c24c055
Create Date: 2015-05-02 10:11:46.095370

"""

# revision identifiers, used by Alembic.
revision = '30dcafee101'
down_revision = '2474c24c055'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('response_form', sa.Integer(), nullable=True),
    sa.Column('response_content', sa.Integer(), nullable=True),
    sa.Column('art_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['art_id'], ['art.id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    ### end Alembic commands ###
