"""empty message

Revision ID: 34373cdae26
Revises: 2926c7cbb64
Create Date: 2015-05-02 10:06:35.643898

"""

# revision identifiers, used by Alembic.
revision = '34373cdae26'
down_revision = '2926c7cbb64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('session_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'session_id')
    ### end Alembic commands ###
