"""empty message

Revision ID: 347a034b94
Revises: 5130c324be3
Create Date: 2015-04-26 16:38:39.078185

"""

# revision identifiers, used by Alembic.
revision = '347a034b94'
down_revision = '5130c324be3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('art', 'garbage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('garbage', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
