"""empty message

Revision ID: 3afda76bc34
Revises: 34373cdae26
Create Date: 2015-05-02 10:09:22.787176

"""

# revision identifiers, used by Alembic.
revision = '3afda76bc34'
down_revision = '34373cdae26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
