"""empty message

Revision ID: 3c3d260027e
Revises: 347a034b94
Create Date: 2015-04-26 16:40:54.605776

"""

# revision identifiers, used by Alembic.
revision = '3c3d260027e'
down_revision = '347a034b94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('title', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('art', 'title')
    ### end Alembic commands ###
