"""empty message

Revision ID: 4d2e5fcbe2e
Revises: 6e461de098
Create Date: 2015-04-28 08:44:18.648384

"""

# revision identifiers, used by Alembic.
revision = '4d2e5fcbe2e'
down_revision = '6e461de098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('val', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###
