"""empty message

Revision ID: 5130c324be3
Revises: 5a05c27585a
Create Date: 2015-04-26 16:20:28.685387

"""

# revision identifiers, used by Alembic.
revision = '5130c324be3'
down_revision = '5a05c27585a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('garbage', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('art', 'garbage')
    ### end Alembic commands ###
