"""empty message

Revision ID: 5a05c27585a
Revises: None
Create Date: 2015-04-26 16:19:24.422681

"""

# revision identifiers, used by Alembic.
revision = '5a05c27585a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_path')
    )
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('response_form', sa.Integer(), nullable=True),
    sa.Column('response_content', sa.Integer(), nullable=True),
    sa.Column('art_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['art_id'], ['art.id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('art')
    ### end Alembic commands ###
