"""empty message

Revision ID: 6e461de098
Revises: 3b30c0a65fb
Create Date: 2015-04-28 08:41:13.842349

"""

# revision identifiers, used by Alembic.
revision = '6e461de098'
down_revision = '3b30c0a65fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
