"""empty message

Revision ID: b8819af8e1
Revises: 106d46b71b2
Create Date: 2015-04-28 09:06:04.029166

"""

# revision identifiers, used by Alembic.
revision = 'b8819af8e1'
down_revision = '106d46b71b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('response_user_id_fkey', 'response', type_='foreignkey')
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('user_user_id_seq'::regclass)"), nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'authenticated')
    op.create_foreign_key('response_user_id_fkey', 'response', 'user', ['user_id'], ['user_id'])
    ### end Alembic commands ###
