"""empty message

Revision ID: c39454cd62
Revises: 2007f71734e
Create Date: 2015-04-28 09:09:30.045114

"""

# revision identifiers, used by Alembic.
revision = 'c39454cd62'
down_revision = '2007f71734e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
